// Generated by build/write_buildflag_header.py
// From "//base:debugging_buildflags"

#ifndef BASE_DEBUG_DEBUGGING_BUILDFLAGS_H_
#define BASE_DEBUG_DEBUGGING_BUILDFLAGS_H_

#include "build/buildflag.h" // IWYU pragma: export

// IWYU pragma: always_keep

#define BUILDFLAG_INTERNAL_EXPENSIVE_DCHECKS_ARE_ON() (0)

#endif  // BASE_DEBUG_DEBUGGING_BUILDFLAGS_H_
