#!/usr/bin/env bash

set -euo pipefail

upstream_url='https://chromium.googlesource.com/chromium/src'
revision='54a349ce38a4678281c4a0863824e8aeee30fc5f'
checkout_dirs=(
  'base'
  'build'
  'testing'
  'third_party/rust'
)
files=(
  '.clang-format'
  '.clang-tidy'
  'DEPS'
  'LICENSE'
  'base/allocator/partition_allocator/src/partition_alloc/build_config.h'
  'base/allocator/partition_allocator/src/partition_alloc/buildflag.h'
  'base/allocator/partition_allocator/src/partition_alloc/flags.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/augmentations/compiler_specific.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/bit_cast.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/bits.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/bits_pa_unittest.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/check.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/check.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/compiler_specific.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/component_export.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/component_export_pa_unittest.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/cpu.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/cpu.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/cpu_pa_unittest.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/cxx20_is_constant_evaluated.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/cxx_wrapper/algorithm.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/debug/alias.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/debug/alias.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/debug/stack_trace.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/debug/stack_trace.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/debug/stack_trace_android.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/debug/stack_trace_linux.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/debug/stack_trace_mac.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/debug/stack_trace_posix.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/debug/stack_trace_win.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/immediate_crash.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/log_message.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/log_message.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/logging.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/logging.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/logging_pa_unittest.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/notreached.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/numerics/checked_math.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/numerics/checked_math_impl.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/numerics/clamped_math.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/numerics/clamped_math_impl.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/numerics/safe_conversions.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/numerics/safe_conversions_arm_impl.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/numerics/safe_conversions_impl.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/numerics/safe_math.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/numerics/safe_math_arm_impl.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/numerics/safe_math_clang_gcc_impl.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/numerics/safe_math_shared_impl.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/posix/eintr_wrapper.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/posix/safe_strerror.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/posix/safe_strerror.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/process/process_handle.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/process/process_handle_posix.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/process/process_handle_win.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/scoped_clear_last_error.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/scoped_clear_last_error_pa_unittest.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/scoped_clear_last_error_win.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/strings/cstring_builder.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/strings/cstring_builder.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/strings/cstring_builder_pa_unittest.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/strings/safe_sprintf.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/strings/safe_sprintf.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/strings/safe_sprintf_pa_unittest.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/strings/string_util.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/strings/string_util.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/strings/string_util_pa_unittest.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/strings/stringprintf.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/strings/stringprintf.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/strings/stringprintf_pa_unittest.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/thread_annotations.h'
  # 'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/thread_annotations_pa_nocompile.nc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/thread_annotations_pa_unittest.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/threading/platform_thread.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/threading/platform_thread.h'
  # 'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/threading/platform_thread_android_for_testing.cc'
  # 'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/threading/platform_thread_apple_for_testing.mm'
  # 'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/threading/platform_thread_for_testing.h'
  # 'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/threading/platform_thread_fuchsia_for_testing.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/threading/platform_thread_internal_posix.h'
  # 'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/threading/platform_thread_linux_for_testing.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/threading/platform_thread_posix.cc'
  # 'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/threading/platform_thread_posix_for_testing.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/threading/platform_thread_ref.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/threading/platform_thread_win.cc'
  # 'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/threading/platform_thread_win_for_testing.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/time/time.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/time/time.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/time/time_apple.mm'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/time/time_conversion_posix.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/time/time_fuchsia.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/time/time_now_posix.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/time/time_override.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/time/time_override.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/time/time_win.cc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/types/same_as_any.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/win/win_handle_types.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/win/win_handle_types_list.inc'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_base/win/windows_types.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_config.h'
  'base/allocator/partition_allocator/src/partition_alloc/partition_alloc_forward.h'
  'base/allocator/partition_allocator/src/partition_alloc/pointers/instance_tracer.cc'
  'base/allocator/partition_allocator/src/partition_alloc/pointers/instance_tracer.h'
  'base/allocator/partition_allocator/src/partition_alloc/pointers/raw_ptr.h'
  'base/allocator/partition_allocator/src/partition_alloc/pointers/raw_ptr_exclusion.h'
  # 'base/allocator/partition_allocator/src/partition_alloc/pointers/raw_ptr_nocompile.nc'
  'base/allocator/partition_allocator/src/partition_alloc/pointers/raw_ptr_noop_impl.h'
  # 'base/allocator/partition_allocator/src/partition_alloc/pointers/raw_ptr_unittest.cc'
  'base/allocator/partition_allocator/src/partition_alloc/pointers/raw_ref.h'
  # 'base/allocator/partition_allocator/src/partition_alloc/pointers/raw_ref_nocompile.nc'
  # 'base/allocator/partition_allocator/src/partition_alloc/pointers/raw_ref_unittest.cc'
  'base/apple/bridging.h'
  'base/apple/bundle_locations.h'
  'base/apple/bundle_locations.mm'
  'base/apple/foundation_util.h'
  'base/apple/foundation_util.mm'
  'base/apple/foundation_util_unittest.mm'
  'base/apple/scoped_cftyperef.h'
  'base/apple/scoped_cftyperef_unittest.cc'
  'base/apple/scoped_mach_port.cc'
  'base/apple/scoped_mach_port.h'
  'base/apple/scoped_typeref.h'
  'base/atomic_ref_count.h'
  'base/base_export.h'
  'base/bit_cast.h'
  'base/bit_cast_unittest.cc'
  'base/bits.h'
  'base/command_line.cc'
  'base/command_line.h'
  # 'base/command_line_fuzzer.cc'
  'base/command_line_unittest.cc'
  'base/compiler_specific.h'
  'base/containers/adapters.h'
  'base/containers/adapters_internal.h'
  # 'base/containers/adapters_nocompile.nc'
  'base/containers/adapters_unittest.cc'
  'base/containers/checked_iterators.h'
  # 'base/containers/checked_iterators_nocompile.nc'
  'base/containers/checked_iterators_unittest.cc'
  'base/containers/circular_deque.h'
  # 'base/containers/circular_deque_unittest.cc'
  'base/containers/contains.h'
  # 'base/containers/contains_nocompile.nc'
  'base/containers/contains_unittest.cc'
  'base/containers/flat_map.h'
  # 'base/containers/flat_map_unittest.cc'
  'base/containers/flat_set.h'
  # 'base/containers/flat_set_unittest.cc'
  'base/containers/flat_tree.h'
  # 'base/containers/flat_tree_unittest.cc'
  'base/containers/heap_array.h'
  # 'base/containers/heap_array_nocompile.nc'
  'base/containers/heap_array_unittest.cc'
  'base/containers/map_util.h'
  'base/containers/map_util_unittest.cc'
  'base/containers/span.h'
  'base/containers/span_forward_internal.h'
  # 'base/containers/span_nocompile.nc'
  'base/containers/span_unittest.cc'
  'base/containers/span_writer.h'
  'base/containers/span_writer_unittest.cc'
  'base/containers/stack.h'
  'base/containers/to_vector.h'
  # 'base/containers/to_vector_nocompile.nc'
  'base/containers/to_vector_unittest.cc'
  'base/containers/vector_buffer.h'
  # 'base/containers/vector_buffer_unittest.cc'
  'base/cpu.cc'
  'base/cpu.h'
  'base/cpu_unittest.cc'
  'base/dcheck_is_on.h'
  'base/debug/alias.cc'
  'base/debug/alias.h'
  'base/debug/alias_unittest.cc'
  'base/environment.cc'
  'base/environment.h'
  'base/environment_unittest.cc'
  'base/files/file_path.cc'
  'base/files/file_path.h'
  # 'base/files/file_path_fuzzer.cc'
  'base/files/file_path_unittest.cc'
  'base/files/platform_file.h'
  'base/files/safe_base_name.cc'
  'base/files/safe_base_name.h'
  'base/files/safe_base_name_unittest.cc'
  'base/files/scoped_file.cc'
  'base/files/scoped_file.h'
  'base/files/scoped_file_android.cc'
  'base/files/scoped_file_linux.cc'
  # 'base/files/scoped_file_linux_unittest.cc'
  'base/format_macros.h'
  'base/functional/bind.h'
  'base/functional/bind_internal.h'
  # 'base/functional/bind_nocompile.nc'
  # 'base/functional/bind_unittest.cc'
  'base/functional/callback.h'
  'base/functional/callback_forward.h'
  'base/functional/callback_helpers.cc'
  'base/functional/callback_helpers.h'
  'base/functional/callback_helpers_unittest.cc'
  'base/functional/callback_internal.cc'
  'base/functional/callback_internal.h'
  # 'base/functional/callback_nocompile.nc'
  'base/functional/callback_tags.h'
  # 'base/functional/callback_unittest.cc'
  'base/functional/function_ref.h'
  # 'base/functional/function_ref_nocompile.nc'
  'base/functional/function_ref_unittest.cc'
  'base/functional/unretained_traits.h'
  'base/gtest_prod_util.h'
  'base/hash/hash.cc'
  'base/hash/hash.h'
  # 'base/hash/hash_perftest.cc'
  'base/hash/hash_unittest.cc'
  'base/immediate_crash.h'
  # 'base/immediate_crash_unittest.cc'
  'base/json/json_common.h'
  'base/json/json_reader.cc'
  'base/json/json_reader.h'
  # 'base/json/json_reader_fuzzer.cc'
  # 'base/json/json_reader_unittest.cc'
  'base/json/json_writer.cc'
  'base/json/json_writer.h'
  'base/json/json_writer_unittest.cc'
  'base/json/string_escape.cc'
  'base/json/string_escape.h'
  # 'base/json/string_escape_fuzzer.cc'
  'base/json/string_escape_unittest.cc'
  'base/macros/concat.h'
  'base/macros/if.h'
  'base/macros/is_empty.h'
  'base/macros/is_empty_unittest.cc'
  'base/macros/remove_parens.h'
  'base/macros/uniquify.h'
  'base/memory/page_size.h'
  'base/memory/page_size_posix.cc'
  'base/memory/page_size_win.cc'
  'base/memory/protected_memory.h'
  # 'base/memory/protected_memory_nocompile.nc'
  'base/memory/protected_memory_posix.cc'
  'base/memory/protected_memory_unittest.cc'
  'base/memory/protected_memory_win.cc'
  'base/memory/ptr_util.h'
  'base/memory/ptr_util_unittest.cc'
  'base/memory/raw_ptr.h'
  'base/memory/raw_ptr_exclusion.h'
  'base/memory/raw_ref.h'
  'base/memory/raw_span.h'
  'base/memory/raw_span_unittest.cc'
  'base/memory/ref_counted.cc'
  'base/memory/ref_counted.h'
  # 'base/memory/ref_counted_nocompile.nc'
  'base/memory/ref_counted_unittest.cc'
  'base/memory/safe_ref.h'
  'base/memory/safe_ref_traits.h'
  # 'base/memory/safe_ref_unittest.cc'
  'base/memory/scoped_policy.h'
  'base/memory/scoped_refptr.h'
  'base/memory/stack_allocated.h'
  'base/memory/weak_ptr.cc'
  'base/memory/weak_ptr.h'
  # 'base/memory/weak_ptr_nocompile.nc'
  # 'base/memory/weak_ptr_unittest.cc'
  'base/no_destructor.h'
  # 'base/no_destructor_nocompile.nc'
  # 'base/no_destructor_unittest.cc'
  'base/numerics/basic_ops_impl.h'
  'base/numerics/byte_conversions.h'
  'base/numerics/byte_conversions_unittest.cc'
  'base/numerics/checked_math.h'
  'base/numerics/checked_math_impl.h'
  'base/numerics/clamped_math.h'
  'base/numerics/clamped_math_impl.h'
  'base/numerics/integral_constant_like.h'
  'base/numerics/safe_conversions.h'
  'base/numerics/safe_conversions_arm_impl.h'
  'base/numerics/safe_conversions_impl.h'
  'base/numerics/safe_math.h'
  'base/numerics/safe_math_arm_impl.h'
  'base/numerics/safe_math_clang_gcc_impl.h'
  'base/numerics/safe_math_shared_impl.h'
  'base/posix/eintr_wrapper.h'
  'base/posix/safe_strerror.cc'
  'base/posix/safe_strerror.h'
  'base/posix/sysctl.cc'
  'base/posix/sysctl.h'
  'base/posix/sysctl_unittest.cc'
  'base/process/process_handle.cc'
  'base/process/process_handle.h'
  # 'base/process/process_handle_freebsd.cc'
  # 'base/process/process_handle_fuchsia.cc'
  # 'base/process/process_handle_linux.cc'
  # 'base/process/process_handle_mac.cc'
  # 'base/process/process_handle_openbsd.cc'
  'base/process/process_handle_posix.cc'
  'base/process/process_handle_win.cc'
  'base/scoped_clear_last_error.h'
  'base/scoped_clear_last_error_unittest.cc'
  'base/scoped_clear_last_error_win.cc'
  'base/scoped_generic.h'
  'base/scoped_generic_unittest.cc'
  # 'base/sequence_checker.cc'
  'base/sequence_checker.h'
  # 'base/sequence_checker_impl.cc'
  # 'base/sequence_checker_impl.h'
  # 'base/sequence_checker_nocompile.nc'
  # 'base/sequence_checker_unittest.cc'
  'base/strings/cstring_view.h'
  # 'base/strings/cstring_view_nocompile.nc'
  'base/strings/cstring_view_unittest.cc'
  'base/strings/span_printf.h'
  # 'base/strings/span_printf_nocompile.nc'
  'base/strings/span_printf_unittest.cc'
  'base/strings/strcat.cc'
  'base/strings/strcat.h'
  'base/strings/strcat_internal.h'
  'base/strings/strcat_unittest.cc'
  'base/strings/strcat_win.cc'
  'base/strings/strcat_win.h'
  'base/strings/string_number_conversions.cc'
  'base/strings/string_number_conversions.h'
  # 'base/strings/string_number_conversions_fuzzer.cc'
  'base/strings/string_number_conversions_internal.h'
  'base/strings/string_number_conversions_unittest.cc'
  'base/strings/string_number_conversions_win.cc'
  'base/strings/string_number_conversions_win.h'
  'base/strings/string_split.cc'
  'base/strings/string_split.h'
  'base/strings/string_split_internal.h'
  # 'base/strings/string_split_nocompile.nc'
  'base/strings/string_split_unittest.cc'
  'base/strings/string_split_win.cc'
  'base/strings/string_split_win.h'
  'base/strings/string_tokenizer.h'
  # 'base/strings/string_tokenizer_fuzzer.cc'
  'base/strings/string_tokenizer_unittest.cc'
  'base/strings/string_util.cc'
  'base/strings/string_util.h'
  'base/strings/string_util_constants.cc'
  'base/strings/string_util_impl_helpers.h'
  'base/strings/string_util_internal.h'
  # 'base/strings/string_util_perftest.cc'
  'base/strings/string_util_posix.h'
  'base/strings/string_util_unittest.cc'
  'base/strings/string_util_win.cc'
  'base/strings/string_util_win.h'
  'base/strings/string_view_rust.h'
  'base/strings/string_view_util.h'
  # 'base/strings/string_view_util_nocompile.nc'
  'base/strings/string_view_util_unittest.cc'
  'base/strings/stringprintf.cc'
  'base/strings/stringprintf.h'
  'base/strings/stringprintf_unittest.cc'
  'base/strings/sys_string_conversions.h'
  'base/strings/sys_string_conversions_apple.mm'
  'base/strings/sys_string_conversions_apple_unittest.mm'
  # 'base/strings/sys_string_conversions_fuzzer.cc'
  'base/strings/sys_string_conversions_posix.cc'
  'base/strings/sys_string_conversions_unittest.cc'
  'base/strings/sys_string_conversions_win.cc'
  'base/strings/to_string.cc'
  'base/strings/to_string.h'
  'base/strings/to_string_unittest.cc'
  'base/strings/utf_ostream_operators.cc'
  'base/strings/utf_ostream_operators.h'
  'base/strings/utf_string_conversion_utils.cc'
  'base/strings/utf_string_conversion_utils.h'
  'base/strings/utf_string_conversion_utils_unittest.cc'
  'base/strings/utf_string_conversions.cc'
  'base/strings/utf_string_conversions.h'
  # 'base/strings/utf_string_conversions_fuzzer.cc'
  'base/strings/utf_string_conversions_unittest.cc'
  'base/synchronization/atomic_flag.cc'
  'base/synchronization/atomic_flag.h'
  # 'base/synchronization/atomic_flag_unittest.cc'
  'base/synchronization/lock.cc'
  'base/synchronization/lock.h'
  'base/synchronization/lock_impl.h'
  'base/synchronization/lock_impl_posix.cc'
  'base/synchronization/lock_impl_win.cc'
  # 'base/synchronization/lock_nocompile.nc'
  # 'base/synchronization/lock_perftest.cc'
  'base/synchronization/lock_subtle.h'
  # 'base/synchronization/lock_unittest.cc'
  'base/test/gmock_expected_support.h'
  'base/test/gmock_expected_support_unittest.cc'
  'base/test/scoped_locale.cc'
  'base/test/scoped_locale.h'
  'base/third_party/cityhash/COPYING'
  'base/third_party/cityhash/README'
  'base/third_party/cityhash/README.chromium'
  'base/third_party/cityhash/city.cc'
  'base/third_party/cityhash/city.h'
  'base/third_party/double_conversion/LICENSE'
  'base/third_party/double_conversion/README.chromium'
  'base/third_party/double_conversion/double-conversion/bignum-dtoa.cc'
  'base/third_party/double_conversion/double-conversion/bignum-dtoa.h'
  'base/third_party/double_conversion/double-conversion/bignum.cc'
  'base/third_party/double_conversion/double-conversion/bignum.h'
  'base/third_party/double_conversion/double-conversion/cached-powers.cc'
  'base/third_party/double_conversion/double-conversion/cached-powers.h'
  'base/third_party/double_conversion/double-conversion/diy-fp.h'
  'base/third_party/double_conversion/double-conversion/double-conversion.h'
  'base/third_party/double_conversion/double-conversion/double-to-string.cc'
  'base/third_party/double_conversion/double-conversion/double-to-string.h'
  'base/third_party/double_conversion/double-conversion/fast-dtoa.cc'
  'base/third_party/double_conversion/double-conversion/fast-dtoa.h'
  'base/third_party/double_conversion/double-conversion/fixed-dtoa.cc'
  'base/third_party/double_conversion/double-conversion/fixed-dtoa.h'
  'base/third_party/double_conversion/double-conversion/ieee.h'
  'base/third_party/double_conversion/double-conversion/string-to-double.cc'
  'base/third_party/double_conversion/double-conversion/string-to-double.h'
  'base/third_party/double_conversion/double-conversion/strtod.cc'
  'base/third_party/double_conversion/double-conversion/strtod.h'
  'base/third_party/double_conversion/double-conversion/utils.h'
  'base/third_party/icu/LICENSE'
  'base/third_party/icu/README.chromium'
  'base/third_party/icu/icu_utf.h'
  'base/third_party/nspr/LICENSE'
  'base/third_party/nspr/README.chromium'
  'base/third_party/nspr/prtime.cc'
  'base/third_party/nspr/prtime.h'
  'base/third_party/superfasthash/LICENSE'
  'base/third_party/superfasthash/README.chromium'
  'base/third_party/superfasthash/superfasthash.c'
  'base/thread_annotations.h'
  # 'base/thread_annotations_nocompile.nc'
  'base/thread_annotations_unittest.cc'
  # 'base/threading/platform_thread.cc'
  'base/threading/platform_thread.h'
  # 'base/threading/platform_thread_android.cc'
  'base/threading/platform_thread_apple.mm'
  # 'base/threading/platform_thread_cros.cc'
  # 'base/threading/platform_thread_fuchsia.cc'
  # 'base/threading/platform_thread_internal_posix.cc'
  # 'base/threading/platform_thread_internal_posix.h'
  # 'base/threading/platform_thread_linux.cc'
  # 'base/threading/platform_thread_linux_base.cc'
  'base/threading/platform_thread_posix.cc'
  'base/threading/platform_thread_ref.cc'
  'base/threading/platform_thread_ref.h'
  # 'base/threading/platform_thread_unittest.cc'
  'base/threading/platform_thread_win.cc'
  # 'base/threading/platform_thread_win.h'
  # 'base/threading/platform_thread_win_unittest.cc'
  'base/threading/thread_collision_warner.cc'
  'base/threading/thread_collision_warner.h'
  # 'base/threading/thread_collision_warner_unittest.cc'
  # 'base/time/clock.cc'
  # 'base/time/clock.h'
  # 'base/time/default_clock.cc'
  # 'base/time/default_clock.h'
  # 'base/time/default_tick_clock.cc'
  # 'base/time/default_tick_clock.h'
  'base/time/pr_time_unittest.cc'
  # 'base/time/tick_clock.cc'
  # 'base/time/tick_clock.h'
  'base/time/time.cc'
  'base/time/time.h'
  'base/time/time_android.cc'
  'base/time/time_apple.mm'
  'base/time/time_apple_unittest.mm'
  'base/time/time_conversion_posix.cc'
  # 'base/time/time_delta_from_string.cc'
  # 'base/time/time_delta_from_string.h'
  # 'base/time/time_delta_from_string_fuzzer.cc'
  # 'base/time/time_delta_from_string_unittest.cc'
  # 'base/time/time_exploded_icu.cc'
  'base/time/time_exploded_posix.cc'
  # 'base/time/time_fuchsia.cc'
  # 'base/time/time_fuzzer.cc'
  'base/time/time_now_posix.cc'
  'base/time/time_override.cc'
  'base/time/time_override.h'
  # 'base/time/time_unittest.cc'
  'base/time/time_win.cc'
  # 'base/time/time_win_perftest.cc'
  # 'base/time/time_win_unittest.cc'
  'base/timer/elapsed_timer.cc'
  'base/timer/elapsed_timer.h'
  'base/timer/elapsed_timer_unittest.cc'
  # 'base/timer/hi_res_timer_manager.h'
  # 'base/timer/hi_res_timer_manager_posix.cc'
  # 'base/timer/hi_res_timer_manager_unittest.cc'
  # 'base/timer/hi_res_timer_manager_win.cc'
  # 'base/timer/lap_timer.cc'
  # 'base/timer/lap_timer.h'
  # 'base/timer/lap_timer_unittest.cc'
  # 'base/timer/mock_timer.cc'
  # 'base/timer/mock_timer.h'
  # 'base/timer/mock_timer_unittest.cc'
  # 'base/timer/timer.cc'
  # 'base/timer/timer.h'
  # 'base/timer/timer_unittest.cc'
  # 'base/timer/wall_clock_timer.cc'
  # 'base/timer/wall_clock_timer.h'
  # 'base/timer/wall_clock_timer_unittest.cc'
  'base/types/always_false.h'
  'base/types/cxx23_from_range.h'
  'base/types/cxx23_to_underlying.h'
  'base/types/cxx23_to_underlying_unittest.cc'
  'base/types/expected.h'
  'base/types/expected_internal.h'
  'base/types/expected_macros.h'
  # 'base/types/expected_macros_nocompile.nc'
  # 'base/types/expected_macros_perftest.cc'
  'base/types/expected_macros_unittest.cc'
  'base/types/expected_unittest.cc'
  'base/types/is_complete.h'
  'base/types/is_complete_unittest.cc'
  'base/types/is_instantiation.h'
  'base/types/is_instantiation_unittest.cc'
  'base/types/pass_key.h'
  # 'base/types/pass_key_nocompile.nc'
  'base/types/pass_key_unittest.cc'
  'base/types/same_as_any.h'
  'base/types/same_as_any_unittest.cc'
  'base/types/strong_alias.h'
  'base/types/strong_alias_unittest.cc'
  'base/types/supports_ostream_operator.h'
  'base/types/supports_ostream_operator_unittest.cc'
  'base/types/supports_to_string.h'
  'base/types/to_address.h'
  'base/types/to_address_unittest.cc'
  'base/value_iterators.cc'
  'base/value_iterators.h'
  'base/value_iterators_unittest.cc'
  'base/values.cc'
  'base/values.h'
  # 'base/values_nocompile.nc'
  'base/values_unittest.cc'
  'base/version.cc'
  'base/version.h'
  'base/version_unittest.cc'
  'base/win/access_control_list.cc'
  'base/win/access_control_list.h'
  'base/win/access_control_list_unittest.cc'
  'base/win/access_token.cc'
  'base/win/access_token.h'
  'base/win/access_token_unittest.cc'
  'base/win/atl.h'
  'base/win/atl_throw.cc'
  'base/win/atl_throw.h'
  'base/win/scoped_handle.cc'
  'base/win/scoped_handle.h'
  # 'base/win/scoped_handle_test_dll.cc'
  # 'base/win/scoped_handle_unittest.cc'
  'base/win/scoped_localalloc.h'
  'base/win/scoped_localalloc_unittest.cc'
  'base/win/scoped_process_information.cc'
  'base/win/scoped_process_information.h'
  # 'base/win/scoped_process_information_unittest.cc'
  'base/win/security_descriptor.cc'
  'base/win/security_descriptor.h'
  # 'base/win/security_descriptor_unittest.cc'
  'base/win/security_util.cc'
  'base/win/security_util.h'
  # 'base/win/security_util_unittest.cc'
  'base/win/sid.cc'
  'base/win/sid.h'
  'base/win/sid_unittest.cc'
  'base/win/startup_information.cc'
  'base/win/startup_information.h'
  # 'base/win/startup_information_unittest.cc'
  'base/win/win_handle_types.h'
  'base/win/win_handle_types_list.inc'
  'base/win/windows_defines.inc'
  'base/win/windows_handle_util.h'
  'base/win/windows_undefines.inc'
  'base/win/windows_types.h'
  'build/build_config.h'
  'build/buildflag.h'
  'testing/gmock/include/gmock/gmock.h'
  'testing/gtest/include/gtest/gtest.h'
  'testing/gtest/include/gtest/gtest_prod.h'
  'testing/gtest_mac.h'
  'testing/gtest_mac.mm'
  'testing/gtest_mac_unittest.mm'
  'testing/platform_test.h'
  'testing/platform_test_mac.mm'
  'third_party/rust/serde_json_lenient/v0_2/README.chromium'
  'third_party/rust/serde_json_lenient/v0_2/wrapper/functions.h'
  'third_party/rust/serde_json_lenient/v0_2/wrapper/lib.rs'
  'third_party/rust/serde_json_lenient/v0_2/wrapper/visitor.rs'
)

upstream_dir='third_party/chromium-upstream'
out_dir='chromium'

git -C "${upstream_dir}" rev-parse --is-inside-work-tree > /dev/null 2>&1 || {
  git clone --sparse --depth=1 --revision="${revision}" \
    "${upstream_url}" "${upstream_dir}"
  git -C "${upstream_dir}" sparse-checkout set "${checkout_dirs[@]}"
}
current_revision=$(git -C "${upstream_dir}" rev-parse HEAD)
if [[ ${current_revision} != "${revision}" ]]; then
  git -C "${upstream_dir}" fetch --depth=1 origin "${revision}" || {
    echo "Failed to fetch revision ${revision} from ${upstream_url}" >&2
    exit 1
  }
  git -C "${upstream_dir}" checkout "${revision}" || {
    echo "Failed to checkout revision ${revision} in ${upstream_dir}" >&2
    exit 1
  }
fi
if ! git -C "${upstream_dir}" diff --quiet; then
  echo "The repository ${upstream_dir} is dirty" >&2
  exit 1
fi

safe_copy() {
  local src="$1"
  local dst="$2"
  if [[ ! -f ${src} ]]; then
    echo "File ${src} does not exist, skipping." >&2
  elif [[ -e ${dst} ]]; then
    echo "File ${dst} already exists, skipping." >&2
  else
    cp "${src}" "${dst}"
  fi
}

echo "Syncing upstream files to ${out_dir}..." >&2
fd --unrestricted --type=file \
  --exclude='**/BUILD.bazel' \
  --exclude='**/*.bzl' \
  --exec rm -f {} \; \
  . "${out_dir}"
find "${out_dir}" -type d -empty -delete
for file in "${files[@]}"; do
  src="${upstream_dir}/${file}"
  dst="${out_dir}/${file}"
  mkdir -p "$(dirname "${dst}")"
  safe_copy "${src}" "${dst}"
done

cp "${out_dir}/base/threading/platform_thread.h" "${out_dir}/base/threading/platform_thread_handle.h"
cp "${out_dir}/base/threading/platform_thread_posix.cc" "${out_dir}/base/threading/platform_thread_handle_posix.cc"
cp "${out_dir}/base/threading/platform_thread_win.cc" "${out_dir}/base/threading/platform_thread_handle_win.cc"
